apiVersion: 1

datasources:
  - name: Medical PostgreSQL
    type: postgres
    url: postgres:5432
    database: medical_db
    user: medical_user
    secureJsonData:
      password: medical_password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
    uid: medical_postgres